---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2 }

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  TILE_AZ_METRICS_SINGLETON:
  TILE_AZS_METRICS:
 
  
inputs:
  - name: pcf-pipelines

run:
  path: pcf-pipelines/tasks/config-metrics/task.sh
