---

platform: linux

image_resource:
  type: docker-image
  source: {repository: 10.240.199.202/czero/cflinuxfs2, insecure_registries: ["10.240.199.202"]}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  TILE_AZ_SCS_SINGLETON:
  TILE_AZS_SCS:

inputs:
  - name: pcf-pipelines

run:
  path: pcf-pipelines/tasks/config-scs/task.sh
