---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2 }

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  TILE_AZ_SCS_SINGLETON:
  TILE_AZS_SCS:
  SCS_MAX_INSTANCES:
  SCS_BROKER_APP_BUILDPACK:
  SCS_SKIP_SSL_VALIDATION:
  SCS_APP_PUSH_TIMEOUT_MINUTES:

inputs:
  - name: pcf-pipelines

run:
  path: pcf-pipelines/tasks/config-scs/task.sh
