---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: cloudfoundry/cflinuxfs2
 
inputs:
- name: tarball

outputs:
- name: unpacked-tarballs

run: 
 path: sh
 args:
 - -c
 - |
   tar xvf -C unpacked-tarballs tarball/*.tgz
