---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
- name: pcf-pipelines
- name: cf-cli
- name: om
- name: version

outputs:
- name: pcf-pipelines-release-files

run:
  path: sh
  args:
  - -ce
  - |
    version=v$(cat version/version)

    tar \
      --exclude .git \
      --exclude ci \
      --exclude "*.go" \
      --create \
      --gzip \
      --file pcf-pipelines-release-files/pcf-pipelines-$version.tar \
      pcf-pipelines

    gunzip cf-cli/*.tgz

    tar \
      --concatenate \
      --file pcf-pipelines-release-files/pcf-pipelines-$version.tar \
      cf-cli/*.tar

    tar \
      --append
      --file pcf-pipelines-release-files/pcf-pipelines-$version.tar \
      om/om-linux

    gzip pcf-pipelines-release-files/pcf-pipelines-$version.tar
