---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

inputs:
- name: pcf-pipelines
- name: cf-cli
- name: om
- name: version

outputs:
- name: pcf-pipelines-release-files

run:
  path: sh
  args:
  - -ce
  - |
    version=v$(cat version/version)

    tar --extract --file cf-cli/*.tgz

    tar \
      --exclude .git \
      --exclude ci \
      --exclude "*.go" \
      --create \
      --gzip \
      --file pcf-pipelines-release-files/pcf-pipelines-$version.tgz \
      pcf-pipelines \
      cf \
      om/om-linux
