---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: pcf-pipelines
- name: ginkgo
  path: go/src/github.com/onsi/ginkgo
- name: gomega
  path: go/src/github.com/onsi/gomega
- name: yaml
  path: go/src/gopkg.in/yaml.v2

run:
  path: bash
  args:
  - -ce
  - |
    export GOPATH=$PWD/go
    export PATH=$GOPATH/bin:$PATH

    go install github.com/onsi/ginkgo/ginkgo
    go get github.com/Masterminds/glide

    pushd pcf-pipelines
      glide install
      ginkgo -p -r -randomizeAllSpecs
    popd
