---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs2

inputs:
- name: release
- name: version

params:
  PIPELINE_NAME:
  PIPELINE_PATH:
  PIVNET_TOKEN:
  OPSMAN_ADMIN_USERNAME:
  OPSMAN_ADMIN_PASSWORD:
  OPSMAN_URI:
  GITHUB_TOKEN:
  OPSMAN_TIMEOUT_SECONDS:
  ATC_EXTERNAL_URL:
  ATC_BASIC_AUTH_USERNAME:
  ATC_BASIC_AUTH_PASSWORD:
  ATC_TEAM_NAME:
  OPSMAN_MAJOR_MINOR_VERSION:
  CHECK_NEW_OPSMAN_EVERY:
  OPSMAN_PROJECT:
  OPSMAN_ZONE:
  OPSMAN_DISKIMAGE_NAME:
  OPSMAN_GCP_CREDFILE_CONTENTS:
  OPSMAN_VM_IDENTIFIER:

run:
  path: bash
  args:
  - -ce
  - |
    curl \
      --silent \
      --insecure \
      --output fly \
      "${ATC_EXTERNAL_URL}/api/v1/cli?arch=amd64&platform=linux"

    chmod +x fly
    PIPELINE_VERSION=v$(cat version/version)

    ./fly --target self login \
      --insecure \
      --concourse-url "${ATC_EXTERNAL_URL}" \
      --username "${ATC_BASIC_AUTH_USERNAME}" \
      --password "${ATC_BASIC_AUTH_PASSWORD}" \
      --team-name "${ATC_TEAM_NAME}"

    cat > params.yml <<EOF
      check_new_opsman_every: "${CHECK_NEW_OPSMAN_EVERY}"
      github_token: "${GITHUB_TOKEN}"
      opsman_admin_password: "${OPSMAN_ADMIN_PASSWORD}"
      opsman_admin_username: "${OPSMAN_ADMIN_USERNAME}"
      opsman_major_minor_version: "${OPSMAN_MAJOR_MINOR_VERSION}"
      opsman_passphrase: "${OPSMAN_ADMIN_PASSWORD}"
      opsman_timeout_seconds: "${OPSMAN_TIMEOUT_SECONDS}"
      opsman_uri: "${OPSMAN_URI}"
      pivnet_token: "${PIVNET_TOKEN}"
      opsman_gcp_project: "${OPSMAN_PROJECT}"
      opsman_gcp_zone: "${OPSMAN_ZONE}"
      opsman_gcp_diskimage_name: "${OPSMAN_DISKIMAGE_NAME}"
      opsman_gcp_credfile_contents: "${OPSMAN_GCP_CREDFILE_CONTENTS}"
      opsman_gcp_vm_identifier: "${OPSMAN_VM_IDENTIFIER}"
    EOF

    ./fly --target self set-pipeline \
      --non-interactive \
      --pipeline ${PIPELINE_NAME} \
      --config ${PIPELINE_PATH} \
      --load-vars-from params.yml
