# Copyright 2017-Present Pivotal Software, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

pivnet_token: CHANGEME
security_group: CHANGEME
aws_access_key_id: CHANGEME
aws_secret_access_key: CHANGEME
instance_type: CHANGEME
key_name: CHANGEME
subnet_id: CHANGEME
aws_instance_name: CHANGEME
opsman_admin_username: CHANGEME
opsman_admin_password: CHANGEME
opsman_subdomain: CHANGEME
opsman_passphrase: CHANGEME
github_token: CHANGEME
route53_zone_id: CHANGEME
aws_region: CHANGEME
vpc_id: CHANGEME
opsman_uri: CHANGEME
opsman_uri_new: CHANGEME
check_new_opsman_every: CHANGEME
opsman_major_minor_version: CHANGEME
opsman_timeout_seconds: 1200
iaas_type: aws
terraform_zip_url: https://releases.hashicorp.com/terraform/0.8.6/terraform_0.8.6_linux_amd64.zip
