---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2 }

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  NETWORK_NAME:
  TILE_AZS_SSO:
  
inputs:
  - name: pcf-pipelines

run:
  path: pcf-pipelines/tasks/config-sso/task.sh
