---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs2
inputs:
  - name: terraform-zip
  - name: pcf-pipelines 
  - name: pcfawsops-terraform-state-get
  - name: tool-om-beta
params:
  ERT_DOMAIN:
  OPSMAN_USER:
  OPSMAN_PASSWORD:
  AWS_TEMPLATE:
  AWS_KEY_NAME:
  PEM:
  AWS_REGION:
  S3_ENDPOINT:
  ert_subnet_reserved_ranges_z1:
  ert_subnet_reserved_ranges_z2:
  ert_subnet_reserved_ranges_z3:
  services_subnet_reserved_ranges_z1:
  services_subnet_reserved_ranges_z2:
  services_subnet_reserved_ranges_z3:
  infra_subnet_reserved_ranges_z1:
run:
  path: pcf-pipelines/tasks/install-pcf-aws/config-director.sh
