---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker
inputs:
  - name: pcf-pipelines 
  - name: pcfawsops-terraform-state-get
outputs:
  - name: pcfawsops-terraform-state-put
params:
  TF_VAR_aws_access_key:
  TF_VAR_aws_secret_key:
  TF_VAR_aws_key_name:
  TF_VAR_aws_cert_arn:
  TF_VAR_rds_db_username:
  TF_VAR_rds_db_password:
  TF_VAR_environment:
  TF_VAR_opsman_ami:
  TF_VAR_amis_nat:
  TF_VAR_aws_region:
  TF_VAR_az1:
  TF_VAR_az2:
  TF_VAR_az3:
  TF_VAR_route53_zone_id:
  TF_VAR_vpc_cidr:
  TF_VAR_public_subnet_cidr_az1:
  TF_VAR_public_subnet_cidr_az2:
  TF_VAR_public_subnet_cidr_az3:
  TF_VAR_ert_subnet_cidr_az1:
  TF_VAR_ert_subnet_cidr_az2:
  TF_VAR_ert_subnet_cidr_az3:
  TF_VAR_services_subnet_cidr_az1:
  TF_VAR_services_subnet_cidr_az2:
  TF_VAR_services_subnet_cidr_az3:
  TF_VAR_infra_subnet_cidr_az1:
  TF_VAR_rds_subnet_cidr_az1:
  TF_VAR_rds_subnet_cidr_az2:
  TF_VAR_rds_subnet_cidr_az3:
run:
  path: pcf-pipelines/tasks/install-pcf-aws/destroy-aws.sh
