---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker
inputs:
  - name: pcf-pipelines 
  - name: pcfawsops-terraform-state-get
params:
  PEM:
  ERT_DOMAIN:
run:
  path: pcf-pipelines/tasks/install-pcf-aws/prepare-rds.sh
