---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:

inputs:
  - name: pcf-pipelines
  - name: om-cli

run:
  path: pcf-pipelines/tasks/disable-ert-errands/task.sh
