---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PIVNET_API_TOKEN:
  NO_PROXY:
  OM_IP:

inputs:
  - name: pivnet-product
  - name: concourse-vsphere
  - name: om-cli
  - name: pivnet-cli

run:
  path: concourse-vsphere/tasks/upload-product/task.sh
