atc_external_url:
atc_team_name:
aws_cf_api_uri:
aws_cf_password:
aws_cf_user:
fly_basic_auth_password:
fly_basic_auth_username:
github_token:
git_private_key:
iaas_type:
opsman_admin_password:
opsman_admin_username:
opsman_major_minor_version:
opsman_timeout_seconds:
opsman_uri:
pivnet_aws_access_key:
pivnet_aws_secret_key:
pivnet_poll_interval:
pivnet_s3_filepath_prefix:
pivnet_token:
slack_webhook_url:
upgrade_opsman_aws_aws_access_key_id:
upgrade_opsman_aws_aws_region:
upgrade_opsman_aws_aws_secret_access_key:
upgrade_opsman_aws_aws_vpc_id:
upgrade_opsman_aws_existing_opsman_vm_name:
upgrade_opsman_aws_opsman_uri:
upgrade_opsman_aws_opsman_admin_username:
upgrade_opsman_aws_opsman_admin_password:
upgrade_opsman_gcp_opsman_admin_username:
upgrade_opsman_gcp_opsman_admin_password:
upgrade_opsman_gcp_existing_opsman_vm_name:
upgrade_opsman_gcp_opsman_uri:
upgrade_opsman_gcp_opsman_gcp_project:
upgrade_opsman_gcp_opsman_gcp_zone:
upgrade_opsman_gcp_opsman_gcp_diskimage_name:
upgrade_opsman_gcp_opsman_gcp_credfile_contents:
upgrade_opsman_gcp_opsman_major_minor_version:
