atc_external_url:
atc_team_name:
cf_api_uri:
cf_password:
cf_user:
fly_basic_auth_password:
fly_basic_auth_username:
github_token:
iaas_type:
opsman_admin_password:
opsman_admin_username:
opsman_major_minor_version:
opsman_timeout_seconds:
opsman_uri:
pivnet_aws_access_key:
pivnet_aws_secret_key:
pivnet_poll_interval:
pivnet_s3_filepath_prefix:
pivnet_token:
upgrade_opsman_aws_access_key_id:
upgrade_opsman_aws_region:
upgrade_opsman_aws_secret_access_key:
upgrade_opsman_aws_vpc_id:
upgrade_opsman_existing_opsman_vm_name:
