---

platform: linux

image_resource:
  type: docker-image
  source: {repository: 10.240.199.202/czero/cflinuxfs2, insecure_registries: ["10.240.199.202"]}

inputs:
  - name: pcf-pipelines 
  - name: json_file

run:
  path: pcf-pipelines/tasks/install-ert/configure-ert/task.sh

params:
  pcf_iaas:
  pcf_ert_domain:
  pcf_opsman_admin:
  pcf_opsman_admin_passwd:
